import os


class Config:
    def __init__(self):
        self.network = 'resnet50'
        # placeholder fot the class mapping, automatically generated by the parser
        self.class_mapping = None
        self.config_save_file = 'config.pickle'
        self.label_file = '/home/nice/PycharmProjects/RPN_Network/simple_label.txt'
        self.balanced_classes = False
        self.rot_90 = False

        #
        self.use_horizontal_flips = False
        self.use_vertical_flips = False

        # 相对小的一边边长为600
        self.img_size = 600

        # RPN上的步长（取决于网络结构）
        self.rpn_stride = 16

        # anchor box scales
        self.anchor_box_scales = [128, 256]

        # anchor box ratios
        self.anchor_box_ratios = [[1, 1], [1, 2], [2, 1]]

        self.num_anchors = 6

        # bbox区域与anchor的最大最小overlap
        self.rpn_min_overlap = 0.3
        self.rpn_max_overlap = 0.7

        # 图像各个通道的平均值
        self.img_channel_mean = [103.939, 116.779, 123.68]

        # 回归梯度的规整因子
        self.std_scaling = 4.0

        # 加载权重的文件
        # 默认为resnet50
        self.base_net_weights = os.path.join('./model/', 'resnet50_weights_tf_dim_ordering_tf_kernels.h5')

        # 模型路径
        self.model_path = './model/weight_xray.hdf5'

        #
        self.num_epochs = 50

        #
        self.verbose = True

        #
        self.img_scaling_factor = 1.0

        # 设置区域类别数量
        self.num_regions = 4

        # 类别映射
        self.class_map = {'metalcup': 0, 'drink': 1, 'battery': 2, 'computer': 3}